# Generated by Django 6.0.5 on 2026-05-24 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='completed_at',
            new_name='scheduled_at',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='business_type',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_delivered',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_failed',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_sent',
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment_filter',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='trigger_type',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_contacts', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('opted_out_skipped', models.IntegerField(default=0)),
                ('cost_npr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.OneToOneField(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_logs',
            },
        ),
    ]
