# Generated by Django 6.0.5 on 2026-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_completed_at_campaign_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='unique_running_campaign'),
        ),
    ]
